### ISSUE TITLE
Error when trying to build a docker image with self-hosted github runner

### ISSUE THREAD

**Issue by DirkWolthuis** [tcardonne/docker-github-runner#24]
When using the config bellow to try and build a docker image I get an error that the Dockerfile can't be found. Be when running the same script in a Github runner from Github it runs. I've mounted the volume to the container of the self-hosted Github runner:

The error message: `unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /github/workspace/Dockerfile: no such file or directory`

```yml
jobs:
  # This workflow contains a single job called "build"
  build-and-publish-head:
    runs-on: ubuntu-16.04 #self-hosted does not work here. 

    steps:
      - uses: actions/checkout@v2 # Checking out the repo

      - name: Build and Publish head Docker image
        uses: VaultVulp/gp-docker-action@1.1.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: fantasy-map-tool-react # Provide Docker image name
          image-tag: ${{ github.sha }} # Provide Docker image tag
```

Any thoughts?
