### ISSUE TITLE
NotFound from 'POST https://api.github.com/actions/runner-registration'

### ISSUE THREAD

**Issue by ricardoboss** [tcardonne/docker-github-runner#41]
This is the log when using a `docker-compose.yml` and `docker-compose up -d`:

```
runner_1  |
runner_1  | --------------------------------------------------------------------------------
runner_1  | |        ____ _ _   _   _       _          _        _   _                      |
runner_1  | |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
runner_1  | |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
runner_1  | |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
runner_1  | |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
runner_1  | |                                                                              |
runner_1  | |                       Self-hosted runner registration                        |
runner_1  | |                                                                              |
runner_1  | --------------------------------------------------------------------------------
runner_1  |
runner_1  | # Authentication
runner_1  |
runner_1  | Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration'
runner_1  | {"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
runner_1  | Response status code does not indicate success: 404 (Not Found).
runner_1  | .path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
runner_1  | Starting Runner listener with startup type: service
runner_1  | Started listener process
runner_1  | Started running service
runner_1  | An error occurred: Not configured
runner_1  | Runner listener exited with error code 2
runner_1  | Runner listener exit with retryable error, re-launch runner in 5 seconds. 
```

Needless to say that it doesn't even start up. Any idea whats going on?

**Comment by ricardoboss** [comment]
This is my `docker-compose.yml`:

```yaml
version: "3.7"

services:
    runner:
      image: tcardonne/github-runner:latest
      environment:
        RUNNER_NAME: "runner-x"
        RUNNER_REPOSITORY_URL: ${RUNNER_REPOSITORY_URL}
        RUNNER_ORGANIZATION_URL: ${RUNNER_ORGANIZATION_URL}
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
        RUNNER_TOKEN: ${RUNNER_TOKEN}
        RUNNER_LABELS: ${RUNNER_LABELS}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
```
