### ISSUE TITLE
How to defined RUNNER_LABELS in docker-compose file?

### ISSUE THREAD

**Issue by xw185019-ncr** [tcardonne/docker-github-runner#46]
HI , i have create a docker-compose.yaml and try to run the runner with RUNNER_LABELS environment variable, but it doesn't work as expected. 
here is my docker-compose.yaml file

``` yaml
version: "3.7"

services:
    runner:
      image: tcardonne/github-runner:latest
      environment:
        RUNNER_NAME: "my-runner"
        RUNNER_REPOSITORY_URL: ${RUNNER_REPOSITORY_URL}
        #RUNNER_ORGANIZATION_URL: ${RUNNER_ORGANIZATION_URL}
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
        RUNNER_LABELS: "my-runner"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
```

after i docker-compose up, the runner did run successfully but without "my-runner" label attached.

Can you help me with this?

regards
dawnseeker8
